# Numpy Day 2
- Slicing
- Reshapr
- Sorting

In [1]:
import numpy as np


arr = np.array([[1,2,3],[4,5,6]])
print("shape", arr.shape)
print("Dimension",arr.ndim)
print("Size", arr.shape)
print("Dtype", arr.dtype)


shape (2, 3)
Dimension 2
Size (2, 3)
Dtype int64


In [2]:
arr = np.array(["apple", "banana", "mango"])
print (arr.dtype)

<U6


In [10]:
# array reshaping

arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape((3,2)) # reshape ley tuple ma value linxa
reshaped


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
flattened = reshaped.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

In [13]:
raveled = reshaped.ravel()
raveled

array([1, 2, 3, 4, 5, 6])

In [16]:
# transpose

print("Orginal", reshaped)
print('@@@@@@@@')
transposed = reshaped.T
print('\n Transport Array', transposed)

Orginal [[1 2]
 [3 4]
 [5 6]]
@@@@@@@@

 Transport Array [[1 3 5]
 [2 4 6]]


In [18]:
# slicing

arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing", arr[2:7])

Basic Slicing [3 4 5 6 7]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("2D slicing", arr[0:1 ])


2D slicing [[1 2 3]]


In [40]:
arr = np.array([[10,20,30,40],
                 [50,60,70,80],
                 [90,100,110,120]   ])

arr[0:2]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [49]:
# sub matrix
print(arr[0:2 , 0:2])
print(arr[1:3 , 1:3])

[[10 20]
 [50 60]]
[[ 60  70]
 [100 110]]


In [57]:
# entire second row

print(arr[1,:])


[50 60 70 80]


In [60]:
print(arr[ : , 2:])

[[ 30  40]
 [ 70  80]
 [110 120]]


In [ ]:
# reverse rows

print(arr[::-1])

[[ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]


In [62]:
print(arr[ :, ::-1])

[[ 40  30  20  10]
 [ 80  70  60  50]
 [120 110 100  90]]


In [65]:
# Sorting
unsorted = np.array([1,2,3,5,6,9,7,0,8,5,99])

print(np.sort(unsorted))

[ 0  1  2  3  5  5  6  7  8  9 99]


In [75]:
arr_2d_unsorted = np.array([[3,1], [1,2] , [3,2]])
print("Sorted Array", np.sort(arr_2d_unsorted,axis=0))

Sorted Array [[1 1]
 [3 2]
 [3 2]]


In [92]:
# filter

numbers = np.array([1,2,3,4,5,6,7,8,9,0])

even_numbers = numbers[numbers%2 == 0]
even_numbers

array([2, 4, 6, 8, 0])

In [93]:
# filter with mask

mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [6 7 8 9]


In [ ]:
numbers[numbers>=5] = False
print(numbers)

[1 2 3 4 0 0 0 0 0 0]


In [ ]:
# indices
numbers = np.array([1,2,3,4,5,6,7,8,9,0])

indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [ ]:
# where
numbers = np.array([1,2,3,4,5,6,7,8,9])

where_result = np.where(numbers<5) # array ko index position deko ho
print(where_result)

(array([0, 1, 2, 3]),)


In [102]:
# condition array

condition_array = np.where(numbers>5 , numbers*4 , numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36]


In [103]:
# adding and removing data

mat1 = np.array([1,2,3])
mat2 = np.array([5,6,4])

print(mat1 + mat2)

[6 8 7]


In [107]:
combine = np.concatenate((mat1,mat2))
combine

array([1, 2, 3, 5, 6, 4])

In [108]:
mat1.shape

(3,)

In [109]:
mat2.shape

(3,)

In [111]:
mat1.shape == mat2.shape

# if the matrices are compatible then they can be concatenate

True

In [118]:
# add a row in 2x2 matrix

matrix1 = np.array([[1,2],[3,4]])

new_row = np.array([5,6])

print("Initial Matrix\n",matrix1 )
print("New Row\n",new_row )
print("------------------------------\n" )
add_row = np.vstack((matrix1, new_row))

print(add_row)


Initial Matrix
 [[1 2]
 [3 4]]
New Row
 [5 6]
------------------------------

[[1 2]
 [3 4]
 [5 6]]


In [123]:
# new column in 2x2 matrix
matrix1 = np.array([[1,2],[3,4]])

new_col = np.array([[5],[6]])

print("Initial Matrix\n",matrix1 )
print("New col\n",new_col )
print("------------------------------\n" )
add_col = np.hstack((matrix1, new_col))

print(add_col)


Initial Matrix
 [[1 2]
 [3 4]]
New col
 [[5]
 [6]]
------------------------------

[[1 2 5]
 [3 4 6]]


In [133]:
# delete matrix

matrix1 = np.array([1,2 ,3,4])


print("Initial Matrix\n",matrix1 )

deleted = np.delete(matrix1,obj=1)

print(deleted)


Initial Matrix
 [1 2 3 4]
[1 3 4]
