# Day26
- Linear Algebra 
- Element wise matrix operation


In [4]:
import numpy as np

mat1 = np.array([[1,2 ] ,[3 ,4]])
mat2 = np.array([[1,2 ] ,[3 ,4]])

# matrix addition
mat_add = mat1 + mat2
print("Addition" ,mat_add)

# matrix subtraction
mat_sub = mat1 - mat2
print("Subtraction" ,mat_sub)

# matrix multiplication
mat_mux = mat1 @ mat2
print("Multiplication" ,mat_mux)

Addition [[2 4]
 [6 8]]
Subtraction [[0 0]
 [0 0]]
Multiplication [[ 7 10]
 [15 22]]


In [19]:
mat3 =  np.array([[1,2,3]])
mat4 =  np.array([[[1] ,[2],[3]]])

mat5 = mat4 @ mat3
print("shape",mat3.shape )
print("shape",mat4.shape )
print(mat5)

shape (1, 3)
shape (1, 3, 1)
[[[1 2 3]
  [2 4 6]
  [3 6 9]]]


In [25]:
m1 =   np.array([[1,2,3]])
m2 =   np.array([[1,2,3]])
m3 = m1.T

m4 = m3 @ m2

m4


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [30]:
# matrix division

div = m1 / m2
print("division", div)

division [[1. 1. 1.]]


In [29]:
# scalar matrix

scalar = 2
result = mat1 + 2
print(result)

[[3 4]
 [5 6]]


In [31]:
m5 =  np.array([[1,2],[3,4]])
m6 =  np.array([[1],[4]])

m7 = m5 + m6

m7


array([[2, 3],
       [7, 8]])

In [35]:
# Linear ALgebra in Numpy

# 2 * x + y = 5
# x+ 3y = 6

A = np.array([[2,1] , [1,3]])
B = np.array([5,6])

x = np.linalg.solve(A,B)
x

array([1.8, 1.4])

In [44]:

A = np.array([[2,1,6,7,8] , [1,3,6,7,8], [1,3,3,4,2], [1,3,0,8,3] , [5,6,5,2,1]])
B = np.array([5,6,5,6,7])
x = np.linalg.solve(A,B)
x

array([ 0.10666667,  0.55333333,  0.43714286,  0.6752381 , -0.38952381])

In [ ]:
# import numpy as np

# x = np.array([1, 2, 3])
# y = np.array([2, 3, 5])

# X = np.column_stack((x, np.ones_like(x)))


# beta = np.linalg.inv(X.T @ X) @ X.T @ y
# m, c = beta
# print(f"m = {m}, c = {c}")

m = 1.499999999999999, c = 0.3333333333333348
