# Day26
- Linear Algebra 
- Element wise matrix operation


In [4]:
import numpy as np

mat1 = np.array([[1,2 ] ,[3 ,4]])
mat2 = np.array([[1,2 ] ,[3 ,4]])

# matrix addition
mat_add = mat1 + mat2
print("Addition" ,mat_add)

# matrix subtraction
mat_sub = mat1 - mat2
print("Subtraction" ,mat_sub)

# matrix multiplication
mat_mux = mat1 @ mat2
print("Multiplication" ,mat_mux)

Addition [[2 4]
 [6 8]]
Subtraction [[0 0]
 [0 0]]
Multiplication [[ 7 10]
 [15 22]]


In [19]:
mat3 =  np.array([[1,2,3]])
mat4 =  np.array([[[1] ,[2],[3]]])

mat5 = mat4 @ mat3
print("shape",mat3.shape )
print("shape",mat4.shape )
print(mat5)

shape (1, 3)
shape (1, 3, 1)
[[[1 2 3]
  [2 4 6]
  [3 6 9]]]


In [25]:
m1 =   np.array([[1,2,3]])
m2 =   np.array([[1,2,3]])
m3 = m1.T

m4 = m3 @ m2

m4


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [30]:
# matrix division

div = m1 / m2
print("division", div)

division [[1. 1. 1.]]


In [29]:
# scalar matrix

scalar = 2
result = mat1 + 2
print(result)

[[3 4]
 [5 6]]


In [31]:
m5 =  np.array([[1,2],[3,4]])
m6 =  np.array([[1],[4]])

m7 = m5 + m6

m7


array([[2, 3],
       [7, 8]])

In [35]:
# Linear ALgebra in Numpy

# 2 * x + y = 5
# x+ 3y = 6

A = np.array([[2,1] , [1,3]])
B = np.array([5,6])

x = np.linalg.solve(A,B)
x

array([1.8, 1.4])

In [44]:

A = np.array([[2,1,6,7,8] , [1,3,6,7,8], [1,3,3,4,2], [1,3,0,8,3] , [5,6,5,2,1]])
B = np.array([5,6,5,6,7])
x = np.linalg.solve(A,B)
x

array([ 0.10666667,  0.55333333,  0.43714286,  0.6752381 , -0.38952381])

In [ ]:
# import numpy as np

# x = np.array([1, 2, 3])
# y = np.array([2, 3, 5])

# X = np.column_stack((x, np.ones_like(x)))


# beta = np.linalg.inv(X.T @ X) @ X.T @ y
# m, c = beta
# print(f"m = {m}, c = {c}")

m = 1.499999999999999, c = 0.3333333333333348


In [ ]:
# slope 

x = np.array([[1,1] , [2,1] , [3,1]])
y = np.array([2,3,5])

beta = np.linalg.inv(x.T@x)@x.T@y
print(beta)

print("Slope(m) =" , beta[0])
print("Intercept(C) =" , beta[1])


[1.5        0.33333333]
Slope(m) = 1.499999999999999
Intercept(C) = 0.3333333333333348


In [ ]:
# determinante of matrix

x = np.array([[1,1] , [2,1] ])

determinant = np.linalg.det(x)
print(determinant)

-1.0


In [ ]:
# inverse of matrix

y = np.linalg.inv(x).astype(int)
print(y)

[[-1  1]
 [ 2 -1]]


In [69]:
xyz = np.array([[1,2] , [4,5] ])

eigen = np.linalg.eig(xyz)
print(eigen)

EigResult(eigenvalues=array([-0.46410162+0.j,  6.46410162+0.j]), eigenvectors=array([[-0.80689822+0.j, -0.34372377+0.j],
       [ 0.59069049+0.j, -0.9390708 +0.j]]))


In [70]:
u,s,v = np.linalg.svd(A)
print("U matrix = " , u)
print("Sigma values = " , s)
print("V matrix = " , v)


U matrix =  [[-0.57391876 -0.2801358   0.37852641 -0.59632963 -0.30536849]
 [-0.59324272 -0.18314864  0.24654113  0.56624028  0.4828137 ]
 [-0.2855838   0.15862133 -0.16851242  0.49616277 -0.78657945]
 [-0.36393108 -0.19208248 -0.87602853 -0.1961523   0.15734286]
 [-0.32353731  0.90880367  0.01062099 -0.19776171  0.17371531]]
Sigma values =  [20.94655992  7.37736529  5.44677332  1.59211622  0.78354011]
V matrix =  [[-0.19135752 -0.298064   -0.45245648 -0.61446791 -0.54060381]
 [ 0.51063446  0.6130721   0.30365525 -0.31549994 -0.41430463]
 [ 0.00223214 -0.35833088  0.60549113 -0.60321276  0.37564458]
 [-0.82608106  0.51243267  0.20045249 -0.11978789 -0.02173705]
 [ 0.14219652  0.37988444 -0.54431232 -0.38036063  0.62810655]]
