In [5]:
# listData = [1,2,3,4,5]

# multi-dimession

# pip install numpy
# uv add numpy

In [6]:
import numpy as np

In [7]:
arr_1d = np.array([1,2,3,4,5,6])  #1D array
arr_1d

array([1, 2, 3, 4, 5, 6])

In [8]:
arr_2d = np.array([[1,2,3],[4,5,6]])  #2D array
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr_nested = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
arr_nested

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
# List vs Numpy array

#list
py_list  = [1,2,3]
print("Python list multiplication",py_list*2)

Python list multiplication [1, 2, 3, 1, 2, 3]


In [11]:
#numpy
ny_array = np.array([1,2,3])  #element wise multiplication
print("Python list multiplication", ny_array * 2) # 2 is called scalar , we can perform the vector multiplication

Python list multiplication [2 4 6]


In [12]:
arr_2d = np.array([[1,2,3],[1,2,3]])  #2D array
arr_2d

array([[1, 2, 3],
       [1, 2, 3]])

In [1]:
#normal list
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time:", time.time()-start)


 List operation time: 1.0763893127441406


In [3]:
#numpy
import numpy as np
start = time.time()
np_array = np.arange(10000000) * 2
print("\n List operation time:", time.time() -start)


 List operation time: 0.07552385330200195


In [6]:
#Rank 0 (scalar)

a = np.array(10)
a.ndim

0

In [7]:
#Rank 1 (Vector)

a = np.array([1,2,3,4])
a.ndim

1

In [8]:
# Rank 2 (Matrix)

a = np.array([
    [1,2,3],
    [5,6,7]
])
a.ndim

2

In [9]:
a.shape

(2, 3)

In [ ]:
# create the 5 * 5 matix and see the rank

# rank ,shape, ndim, create array

In [11]:
zeros = np.zeros((3,4))
print("Zero array: \n", zeros)

Zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.zeros(shape = (4,5), dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
np.ones(shape = (4,5), dtype = "int8")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [17]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a.sum(axis=0)) #0 = column

[5 7 9]


In [18]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a.sum(axis=1)) #1 =row

[ 6 15]


In [19]:
#random array

random = np.random.random((2,3))
print("random array: \n", random)

random array: 
 [[0.2480915  0.99830358 0.07936612]
 [0.24896117 0.84396468 0.75295538]]


In [22]:
#full

full = np.full((5,2,4),9)
full

array([[[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [27]:
#arange() - create array with a range of values

arr = np.arange(2,10,5)
arr

array([2, 7])

In [36]:
#linespace() - create evenly spaced value

arr = np.linspace(0, 100, 20)
arr

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [37]:
#diag() - create diagonal matrix

arr = np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [39]:
#eye() - create matrix with ones on diagonal

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:

arr = np.eye(3, 5) #can implement in the rectangle matrix
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [43]:
#identity() = create identity matrix. (always square matrix)

arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
#create array of random numbers
arr = np.random.rand(2,3)
arr

array([[0.68513406, 0.3345174 , 0.48247964],
       [0.05947179, 0.26337862, 0.84073699]])